---
- hosts: cdh5-pseudo
  become: yes
  roles:
    - common
    - oracle_jdk
    - cdh_common
    - hadoop
    - zookeeper
    - hbase
    - mariadb
    - mysql_connector_java
    - hive
    - spark
    - impala
